version: "3.9"
services:
  mysql:
    image: "percona/percona-server:8.0"
    ports: 
      - 6603:3306
    Environment:
      - MYSQL-ROOT-PASSWORD=root
  nginx-server:
    - image: nginx:1.13
      ports:
        - "8080:80"
      volumes:
        - './nginx.conf:/etc/nginx/nginx.conf'
       depends_on:
         - appliaction-instance
  application-instance:
    - image: html-server-image:v1
      ports: 
        - "80:80"
      deploy: 
        mode: replicated
        relicas: 2
        
      
